# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stay Home ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stay Home ios
  pod "Firebase/Database"
  pod "Firebase/Auth"
  pod "Firebase/Analytics"

  # Pods for Facebook Login
  pod 'FBSDKLoginKit'

  target 'Stay Home iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Stay Home iosUITests' do
    # Pods for testing
  end

end
